name: Build Site to Github Pages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Build and Deploy
      run: |
        git fetch origin main
        git branch -f gh-pages origin/main
        git checkout gh-pages
        npm install
        npm run build
        if ! git diff-index --quiet HEAD --; then
          git add -f dist
          git commit -m "Deploy to GitHub Pages"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git HEAD:gh-pages --force
        else
          echo "Nothing to deploy"
        fi