name: Build Blog JSON

on:
  push:
    paths:
      - 'blog-posts/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get list of Markdown files
      run: |
        cd blog-posts
        files=($(ls *.md))
        json_array=()
        for file in "${files[@]}"
        do
          name=$(grep '^name: ' "$file" | sed -e 's/^name: //')
          if ! grep -q '^slug: ' "$file"; then
            slug=$(basename "$file" .md)
          else
            slug=$(grep -E '^slug: ' "$file" | sed -e 's/^slug: //')
          fi
          author_name=$(grep -E '^  name: ' "$file" | sed -e 's/^  name: //')
          author_url=$(grep -E '^  url: ' "$file" | sed -e 's/^  url: //')
          description=$(grep -A1 '^description: ' "$file" | tail -1 | tr -d '\n')
          publishedAt=$(grep -E '^publishedAt: ' "$file" | sed -e 's/^publishedAt: //')
          publishedAt=$(echo $publishedAt | sed 's/T.*Z//')
          updatedAt=$(grep -E '^updatedAt: ' "$file" | sed -e 's/^updatedAt: //')
          status=$(grep -E '^status: ' "$file" | sed -e 's/^status: //')
          if [ -z "$status" ]; then
            status="draft"
          fi
          year=$(echo $publishedAt | awk -F'-' '{print $1}')
          month=$(echo $publishedAt | awk -F'-' '{print $2}')
          day=$(echo $publishedAt | awk -F'-' '{print $3}')
          json_array+=("{\"file\":\"$file\",\"year\":\"$year\",\"month\":\"$month\",\"day\":\"$day\",\"name\":\"$name\",\"slug\":\"$slug\",\"author_name\":\"$author_name\",\"author_url\":\"$author_url\",\"description\":\"$description\",\"updatedAt\":\"$updatedAt\",\"publishedAt\":\"$publishedAt\",\"status\":\"$status\"}")
        done
        printf "[%s]" "$(IFS=,; printf '%s\n' "${json_array[@]}")" > ../static/blog.json

    - name: Remove trailing comma
      run: |
        sed -i '$ s/,$//' static/blog.json

    - name: Commit changes
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git add static/blog.json
        git commit -m "Update blog.json"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}