name: Build Blog JSON

on:
  push:
    paths:
      - 'blog-posts/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get list of Markdown files
      run: |
        cd blog-posts
        files=($(ls *.md))
        json_array=()
        for file in "${files[@]}"
        do
          title=$(grep '^title: ' "$file" | sed -e 's/^title: //')
          slug=$(basename "$file" .md)
          date_string=$(grep -E '^date: ' "$file" | cut -d' ' -f2)
          # Use the date command to extract the year, month, and date
          year=$(date -d "$date_string" +%Y)
          month=$(date -d "$date_string" +%m)
          day=$(date -d "$date_string" +%d)
          json_array+=("{\"file\":\"$file\",\"date\":\"$date_string\",\"year\":\"$year\",\"month\":\"$month\",\"day\":\"$day\",\"title\":\"$title\",\"slug\":\"$slug\"}")
        done
        printf "[%s]" "$(IFS=,; printf '%s\n' "${json_array[@]}")" > ../static/blog.json

    - name: Remove trailing comma
      run: |
        sed -i '$ s/,$//' static/blog.json

    - name: Commit changes
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git add static/blog.json
        git commit -m "Update blog.json"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}