name: Build blog.json

on:
  push:
    paths:
      - blog/**/*.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build blog.json
      run: |
        files=$(find blog -name '*.md' -printf '"%f",' | sed '$s/,$//')
        echo "[$files]" > blog.json

    - name: Commit changes
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name "Github Actions"
        git add blog.json
        git commit -m "Build blog.json"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}