name: Build Blog

on:
  push:
    paths:
      - 'blog/**/*.md'

jobs:
  build-blog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build blog.json
      run: |
        files=$(find blog -name '*.md')
        echo "[" > blog.json
        for file in $files; do
          echo "\"$file\"," >> blog.json
        done
        sed -i '$ s/,$//' blog.json
        echo "]" >> blog.json

    - name: Commit and push blog.json
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add blog.json
        git commit -m "Update blog.json"
        git push
