name: Generate Blog JSON

on:
  push:
    paths:
      - blog/**/*.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Blog JSON
      run: |
        echo '[' > blog.json
        for file in blog/*.md; do
          echo "\"${file##*/}\"," >> blog.json
        done
        sed -i '$ s/,$//' blog.json
        echo ']' >> blog.json

    - name: Commit and Push Changes
      uses: actions/git@v3
      with:
        args: commit -am 'Update blog.json' && push

