name: Build Blog JSON

on:
  push:
    paths:
      - 'blog/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get list of Markdown files
      run: |
        cd blog
        files=($(ls -t *.md))
        echo "${files[@]}" > ../blog.json

    - name: Remove trailing comma
      run: |
        sed -i '$ s/,$//' blog.json

    - name: Commit changes
      run: |
        git add blog.json
        git commit -m "Update blog.json"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.GITHUB_REPOSITORY }}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}