name: Build Blog JSON

on:
  push:
    paths:
      - "blog/**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build JSON
      run: |
        file_names=$(ls blog/*.md)
        file_list=''
        for file in $file_names; do
          file_list="$file_list\"$(basename $file)\","
        done
        echo "{\"files\":[${file_list%,}]}" > blog.json

    - name: Commit and push JSON
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "Github Actions"
        git add blog.json
        git commit -m "Update blog.json"
        git push https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git HEAD:$GITHUB_REF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
