name: Build blog.json

on:
  push:
    paths:
      - blog/**/*.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build blog.json
      run: |
        files=$(find blog -name '*.md' -printf '"%f",' | sed '$s/,$//')
        echo "[$files]" > blog.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Github Actions
          author_email: githubactions@github.com
          message: 'Updating blog.json'
          add: 'blog.json'