name: Generate blog.json

on:
  push:
    paths:
      - 'blog/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create blog.json
      run: |
        echo '{ "files": [' > blog.json
        for file in $(find blog -name '*.md' -type f); do
          echo $(basename $file) 
          echo "\"$(basename $file)\"," >> blog.json
        done
        echo ']}' >> blog.json

    - name: Upload blog.json
      uses: actions/upload-artifact@v3
      with:
        name: blog.json
        path: blog.json
